### ISSUE TITLE
Change DB structure / use EF Migrations

### ISSUE THREAD

**Issue by Steini0809** [JeremyLikness/SqliteWasmHelper#25]
Is it possible to use EF migrations? So being able to change the SQLite database structure afterward.

**Comment by JeremyLikness** [comment]
I'm interested in this case. The place the data is stored is in the browser, so not only is there a size restriction, but the user can choose to clear the site data at any time. A migration implies a data structure with existing data that is more permanent and undergoes changes over time that need to preserve the data. I would expect apps using browser storage to be architected in a way that if the data is cleared or the database wiped out, that it can simply recreate and rebuild the data rather than have to migrate. Likewise, if the schema changes, it should be possible to recreate and repopulate the database based on the new schema. 

What's the scenario where a migration becomes necessary?

**Comment by Eddie-Hartman** [comment]
@Steini0809 I made a pr that allows you to optionally specify if you want to use migrations. It's been merged. It just needs to get published to nuget. You can see it here #22 

If you're really eager though, you can download the source and set it up if you don't want to wait.

**Comment by Eddie-Hartman** [comment]
> What's the scenario where a migration becomes necessary?

Speaking to my own case, "necessary" is a strong word, but it certainly is convenient. I'm frequently pushing updates to a PWA that has a limited amount of data. I have a server that it can sync to for more permanent storage, but only when the user is ready to push. They may have changes they have saved locally, but they don't want to share with their team yet. (Yes, I could set up a system to save to the server under their specific user, but it's overkill for what I need.)

If I push an update to both apps (PWA and server) to add a new column to a model, I can expect the PWA with the fork I made to just run the migration script to add that column and I'm good to go. I don't have to worry about having the user have all of their data pushed before making updates or rebuilding after. Or worrying about any kind of backwards compatibility. They don't need to think about it at all and it's super convenient from a dev perspective.

**Comment by JeremyLikness** [comment]
Published NuGet with the latest.
