### ISSUE TITLE
DotNet 9 Support?

### ISSUE THREAD

**Issue by DWhiteR1** [JeremyLikness/SqliteWasmHelper#42]
Hi,
First of all, thank you for this project, much appreciated.
I have changed the .Net version to 9 and am having an Issue...
I added the following to try and debug a bit...
```
   if (!window.Module) {
        console.error("Module in generateDownloadLink is not defined.");
        return false;
    }
```
When I try to add a new record if crashes.
![image](https://github.com/user-attachments/assets/625fe604-ab0d-4646-848d-ba331eb5b716)

Has anyone got this working in .Net 9 preciew 2?
Thanks,
Dean.

**Comment by dest-all** [comment]
@JeremyLikness

**Comment by dest-all** [comment]
@DWhiteR1 
I've found the field we need (Module).
It has moved from window.Module to Blazor.runtime.Module.
You could do `window.Module = window.Blazor.runtime.Module` and thus make your way around it.
Meanwhile I'll try to make a PR with adjustments, so that the code will know that the Module may now reside elsewhere

**Comment by dest-all** [comment]
@JeremyLikness 
I tried to push the transition to .net 9, but I don't have the permission to create new branch in the origin.
Could you grant me it?

**Comment by DWhiteR1** [comment]
> @JeremyLikness I tried to push the transition to .net 9, but I don't have the permission to create new branch in the origin. Could you grant me it?



> @DWhiteR1 I've found the field we need (Module). It has moved from window.Module to Blazor.runtime.Module. You could do `window.Module = window.Blazor.runtime.Module` and thus make your way around it. Meanwhile I'll try to make a PR with adjustments, so that the code will know that the Module may now reside elsewhere

Thank you very much,
I will have a look when I get home tonight.
Much Appreciated.

**Comment by DWhiteR1** [comment]
> @DWhiteR1 I've found the field we need (Module). It has moved from window.Module to Blazor.runtime.Module. You could do `window.Module = window.Blazor.runtime.Module` and thus make your way around it. Meanwhile I'll try to make a PR with adjustments, so that the code will know that the Module may now reside elsewhere

Worked perfectly, thanks again.

**Comment by ysmoradi** [comment]
Greetings
You can leverage latest pre-release of [Bit.Besql](https://bitplatform.dev/besql/overview) nuget [package](https://www.nuget.org/packages/Bit.Besql/).
Here's the list of issues that are resolved among the .NET 9 support:

1- EF Core migrations support: The library should be updated to support EF Core 8's latest features, including migrations, to ensure compatibility with modern development practices.

2- `IDbContextFactory` injection: The library should allow the injection of `IDbContextFactory` instead of `ISqliteWasmDbContextFactory`, enabling developers to share code seamlessly between Blazor hybrid and server applications. The current reliance on `ISqliteWasmDbContextFactory` can be restrictive and even harmful in such scenarios.

3- Simplified database creation and migration: Developers should have a straightforward way to either execute `DbContext.Database.CreateAsync()` or `DbContext.Database.MigrateAsync()` instead of providing an `IMigration` implementation, to simplify database creation and migration processes.
